import Providers from "./components/Providers";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "TrendyPicks",
  description: "Generated by Next.js",
  other: {
    "verify-admitad": "ee0513e4ea",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
